services:
  cv-generator:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./cv_sample.yaml:/app/cv_sample.yaml:ro
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
    restart: unless-stopped