services:
  cv-generator:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./cv_aurelien.yaml:/app/cv_aurelien.yaml:ro  # Montage du CV en lecture seule
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
    restart: unless-stopped