services:
  cv-generator:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data:rw
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
    command: flask run --host=0.0.0.0
    restart: unless-stopped
